#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "4get"
name = "4get"
description.en = "Self-hosted UI serving as proxy to major existing search engines"
description.fr = "Interface auto-hébergeable servant d'intermédiaire avec les principaux moteurs de recherches"

version = "2025.12.14~ynh1"

maintainers = ["oleole39"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://4get.ca"
demo = "https://4get.ca"
admindoc = "https://git.lolcat.ca/lolcat/4get/src/branch/master/docs/configure.md"
userdoc = "https://4get.ca/about"
code = "https://git.lolcat.ca/lolcat/4get"  
fund = "https://4get.ca/donate"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = "not_relevant"
sso = "not_relevant"

disk = "10M"
ram.build = "0M"
ram.runtime = "300M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://git.lolcat.ca/lolcat/4get/archive/92eb6ab14d8c9141a54fedbb7b895c616bf393d6.tar.gz"
    sha256 = "aba7b090ec3e726d301c51a23fbe0e3763af5b20e603df10bde2ef68a6879572"
    autoupdate.strategy = "latest_forgejo_commit"

    [resources.apt]
    packages = ["php8.4-mbstring", "php8.4-imagick", "imagemagick", "php8.4-curl", "curl", "php8.4-apcu"]

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
