#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/tests.v1.schema.json

test_format = 1.0

[default]

test_upgrade_from.d6a5740e65ce51e9e5fe38b645fdd8e012c433fd.name = "Upgrade from 2025.12.14~ynh1"
